### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/water-sensor-api#11]
We probably need some kind of authentication, right?

What about JWT? https://jwt.io/

Here's a blogpost I found (without really reading it): https://www.sitepoint.com/introduction-to-using-jwt-in-rails/

**Comment by dbrgn** [comment]
Here's a blogpost I found (without really reading it): https://www.sitepoint.com/introduction-to-using-jwt-in-rails/

**Comment by dbrgn** [comment]
On the other hand we could also make the API read-only from outside by limiting write access to localhost via Nginx:

```
limit_except GET {
    allow 127.0.0.1/32;
    deny  all;
}
```

http://nginx.org/en/docs/http/ngx_http_core_module.html#limit_except

But we should *at least* have per-app static API tokens. And then we can just as well implement JWT.

**Comment by schmijos** [comment]
Solved with https://github.com/coredump-ch/water-sensor-api/pull/16
