### ISSUE TITLE
Can't create measurements via admin

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/water-sensor-api#12]
What's the reason for this? There's no "Create" button.

**Comment by schmijos** [comment]
Is that needed?

**Comment by dbrgn** [comment]
Well, the form to create a measurement is there, but there's no button :)

**Comment by schmijos** [comment]
ups

**Comment by schmijos** [comment]
Realized with https://github.com/coredump-ch/water-sensor-api/commit/0b7a1e24497646b145dcddf003ba47a1dfcd1709
