### ISSUE TITLE
Sensor <-> Sponsor relationship can't be updated

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/water-sensor-api#14]
I can add sensors to a sponsor, but it is not persisted.

Furthermore, the relation should be the other way around, you should set a sponsor on a sensor, not a list of sensors on a sponsor.

**Comment by schmijos** [comment]
I don't get how the relationship is expected to be the other way around. A sensor belongs to a sponsor (holds foreign key) and a sponsor can have many sensors. Is that wrong?

**Comment by dbrgn** [comment]
No, that's correct :) But right now, you'd add a list of sensor FKs to the sponsor, instead of adding a sponsor FK to the sensor, right?

**Comment by schmijos** [comment]
Only in the GUI. The backend does the correct thing (after the fix)
