### ISSUE TITLE
Setup instructions don't work

### ISSUE THREAD

**Issue by rnestler** [coredump-ch/water-sensor-api#2]
I get an error when trying to run rbenv:
```
% rbenv install
rbenv: no such command `install'
```
What do I need to get rbenv running? I installed it from AUR.

**Comment by rnestler** [comment]
OK I needed ruby-build as an additional dependency.

**Comment by schmijos** [comment]
Aight. Can you PR?

**Comment by rnestler** [comment]
Can do. But I can only write Instructions for [ArchLinux](https://archlinux.org)...

**Comment by schmijos** [comment]
that's a nice to have, right? Maybe a wiki entry?
