### ISSUE TITLE
Private token does not work

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/water-sensor-api#21]
I started the docker-compose environment on my local machine:

    $ docker-compose up

Then, in another window, I created an API consumer:

    $ docker exec -t -i watersensorapi_db_1 /bin/bash
    root@409dc2a34f61:/# su postgres
    $ psql watertemp_api
    watertemp_api=# insert into api_consumers(public_api_key, private_api_key, contact_email, created_at, updated_at)
    watertemp_api-# values('1234pub', '1234priv', 'mail@example.com', now(), now());
    INSERT 0 1

A GET request with an invalid token fails with 401 (correct):

```
$ http GET :3000/api/sensors/ Authorization:"Bearer asdf"
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Vary: Origin
WWW-Authenticate: Token realm="Application"
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: c999815f-87bb-4902-9167-192fb8f6d6d1
X-Runtime: 0.011554
X-XSS-Protection: 1; mode=block

HTTP Token: Access denied.
```

A GET request with the public token works (correct):

```
$ http GET :3000/api/sensors/ Authorization:"Bearer 1234pub"
HTTP/1.1 200 OK
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/json; charset=utf-8
ETag: W/"12998dba8582441d36cd4076bbb2bf06"
Transfer-Encoding: chunked
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 64979a61-5a60-43bf-a7c4-370b2cc57d95
X-Runtime: 0.121913
X-XSS-Protection: 1; mode=block

[
    {
        "caption": "Let's hope this persists.",
        "created_at": "2016-08-04T20:52:06.716Z",
        "device_name": "Test Sensor",
        "id": 1,
        "latitude": null,
        "longitude": null,
        "measurement_ids": [],
        "sponsor_id": null,
        "updated_at": "2016-08-04T20:52:06.716Z",
        "url": "http://localhost:3000/api/sensors/1"
    }
]
```

But a request with the private token fails:

```
$ http GET :3000/api/sensors/ Authorization:"Bearer 1234priv"
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Vary: Origin
WWW-Authenticate: Token realm="Application"
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 3ffad978-1fab-47ad-9524-26eaf3fae548
X-Runtime: 0.001908
X-XSS-Protection: 1; mode=block

HTTP Token: Access denied.
```

**Comment by schmijos** [comment]
As it is now, you cannot access the same resources with an admin key as you can with a public key. I changed that with https://github.com/coredump-ch/water-sensor-api/commit/0b7a1e24497646b145dcddf003ba47a1dfcd1709

Can you tell me how to update docker containers after making code changes?

**Comment by dbrgn** [comment]
Simply run "docker compose up" again. It should automatically rebuild the necessary image.

**Comment by schmijos** [comment]
I tried that. But when I logged in to the code container nothing had changed.

**Comment by dbrgn** [comment]
Hm, maybe `docker-compose up --build`?

**Comment by schmijos** [comment]
This should work now, right?

**Comment by dbrgn** [comment]
Yes, I think so.
