### ISSUE TITLE
Filtering / aggregation of historic measurements

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/water-sensor-api#25]
What options do I have right now to filter measurement data?

Here a few use cases that we need in the app and on the website to be able to display historic data:

- [x] For a sensor, I want the most recent measurement, together with the timestamp
- [x] For a sensor, I want all measurements during the last 24 hours
- [x] For a sensor, I want all measurements between two moments in time
- [x] For a sensor, I want min, max and average temperature for every day in the last 7/14/30 days
- [x] For a sensor, I want min, max and average temperature for every day between two moments in time

Daily averages should probably use the timezone of the sensor.

**Comment by schmijos** [comment]
With PR #29 there are now the following filter parameters:
https://github.com/coredump-ch/water-sensor-api/blob/master/app/controllers/measurements_controller.rb#L10

* sensor_id: comma separated ids
* created_after: lower (exclusive) bound for measurements age
* created_before: upper (exclusive) bound for measurements age
* last_per_sensor: limit amount of measurements per sensor
* last: limit amount of returned measurements

**Comment by schmijos** [comment]
With PR #31 there's a new action for measurements called `aggregated`. It's available for public api keys and returns daily minima, maxima and averages.

**Comment by dbrgn** [comment]
Awesome, I'll try those tonight :)

**Comment by dbrgn** [comment]
@schmijos when inserting garbage (e.g. `asdf`) as `created_after` filter, I get back a HTTP 500 error (at least in development). that should probably become a HTTP 400, right?

Seems to work nicely though otherwise 👍

**Comment by schmijos** [comment]
Should be fixed by #36

**Comment by schmijos** [comment]
The one things still open for all filter parameters is proper error handling: https://github.com/coredump-ch/water-sensor-api/issues/38
