### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/water-sensor-api#33]
Contined discussion from #31.

We need to document that timezones in filter parameters are ignored.

Alternatively, we could also switch to unix timestamps instead of ISO format strings, since the strings are only partially supported and that would give us less of a chance for timezone bugs: Unix timestamps are always relative to UTC.

**Comment by dbrgn** [comment]
A separate but related issue is that the aggregated data per day is calculated in the UTC timezone (if I'm not mistaken), so the daily average is calculated from 23:00-23:00, not from 00:00-24:00, right?

**Comment by schmijos** [comment]
Is this what you meant: #35?
