### ISSUE TITLE
Reason for updated_at

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/water-sensor-api#9]
```json
{
  "id": 1,
  "temperature": "16.0",
  "custom_attributes": {
    "sample_reading": "5.645V"
  },
  "sensor_id": 1,
  "created_at": "2016-07-01T19:45:41.656Z",
  "updated_at": "2016-07-01T19:45:41.656Z",
  "url": "http://x2000:3000/api/measurements/1"
}
```

What's the reason for the `updated_at` field? Do you plan on updating existing measurements?

**Comment by schmijos** [comment]
This is a standard field used by Rails. We could prohibit it from being delivered if you want.

**Comment by dbrgn** [comment]
Yeah, I don't think it's useful. (I'd also remove it from the database.)

**Comment by schmijos** [comment]
Solved here: https://github.com/coredump-ch/water-sensor-api/pull/15/commits/49d83b6f14f7319828b12183ed4895cd634442ce
